version: "3"
services:
    nginx:
        image: nginx:1.21.6
        container_name: "vps-nginx"
        restart: always
        ports:
            - "80:80"
            - "443:443"
        environment:
           - TZ=Asia/Shanghai
        depends_on:
           - "php"
        volumes:
           - "/home/docker-vps/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
           - "/home/docker-vps/log:/var/log"
           - "/home/docker-vps/www:/home/www"
        networks:
           - net-app
    php:
        image: php:7.4.28-fpm
        container_name: "vps-php"
        restart: always
        ports:
            - "9000:9000"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "/home/docker-vps/www:/home/www"
            - "/home/docker-vps/php:/usr/local/etc/php"
        networks:
           - net-app
networks:
    net-app: 
